# Q1 WHAT IS THE GENDER BREAKDOWN OF EMPLOYEE IN THE COMPANY;

SELECT GENDER,COUNT(*) AS COUNT_OF_EMPLOYEES
FROM HR
WHERE AGE>=18 AND TERMDATE IS NULL
GROUP BY GENDER;


#Q2.WHAT IS THE RACE/ETHNICITY BREAKDOWN OF EMPLOYEES IN THE COMPANY?

SELECT RACE,COUNT(*) AS COUNT
FROM HR
WHERE AGE>=18 AND TERMDATE IS NULL
GROUP BY RACE
ORDER BY COUNT DESC;


# Q3. WHAT IS THE AGE DISTRIBUTION OF EMPLOYEES IN THE COMPANY?

SELECT 
MIN(AGE) AS YOUNGEST,
MAX(AGE) AS OLDEST 
FROM HR
WHERE AGE>=18 AND TERMDATE IS NULL;

SELECT CASE
	WHEN AGE >=18 AND AGE<=24 THEN"18 TO 24"
	WHEN AGE >=25 AND AGE<=34 THEN"25 TO 34"
	WHEN AGE >=35 AND AGE<=44 THEN"35 TO 44"
	WHEN AGE >=45 AND AGE<=54 THEN"45 TO 54"
	WHEN AGE >=55 AND AGE<=64 THEN"55 TO 64"
	ELSE "65+"
  END AS AGE_GROUP, GENDER,
  COUNT(*) AS COUNT
  FROM HR
  WHERE AGE >=18 AND TERMDATE IS NULL 
  GROUP BY AGE_GROUP,GENDER
  ORDER BY AGE_GROUP,GENDER  ;
  
  #Q.4 HOW MANY EMPLOYEES WORK AT HEADQUARTERSVERSUS REMOTE LOCATIONS?
  
  SELECT LOCATION , COUNT(LOCATION) AS COUNT
  FROM HR 
  WHERE AGE>=18 AND TERMDATE IS NULL
  GROUP BY LOCATION;
  
  #Q.5 WHAT IS THE AVERAGE LENGTH OF EMPLOYMENT FOR EMPLOYEES WHO HAVE BEEN TERMINATED?
  
  SELECT 
	ROUND(AVG(DATEDIFF(TERMDATE,HIRE_DATE))/365,2) AS AVG_LENGTH_EMPLOYMENT
  FROM HR
  WHERE TERMDATE<=CURDATE() AND TERMDATE <> 0 AND AGE >=18
  
  #MOST OF THEM HAVE BEEN WORKED MORE THAN 7 YEARS;
  
  #Q.6 HOW DOSE THE GENDER DISTRIBUTION VARY ACROSS  THE COMPANY?
 ;
 
 SELECT DEPARTMENT, GENDER , COUNT(*) AS COUNT
 FROM HR
 WHERE AGE >=18 AND TERMDATE IS NULL
 GROUP BY DEPARTMENT,GENDER
 ORDER BY DEPARTMENT;
  
  
  #Q.7 WHAT IS THE DISTRIBUTION OF JOB TITLES ACROSS THE COMPANY?
  
  SELECT JOBTITLE,COUNT(*) AS COUNT
  FROM HR
  WHERE AGE>=18 AND TERMDATE IS NULL
  GROUP BY JOBTITLE
  ORDER BY JOBTITLE DESC;
  
  #8. WHICH DEPT HAS TO HIGHEST TURNOVER RATE?
  
  SELECT DEPARTMENT,
  TOTAL_COUNT,
  TERMINATED_COUNT,
  TERMINATED_COUNTS/TOTAL-COUNT AS TERMINATION_RATE
  FROM(
  SELECT DEPARTMENT,
  COUNT(*) AS TOTAL_COUNT,
  SUM(CASE WHEN TERMDATE IS NOT NULL AND TERMDATE<=CURDATE() THEN 1 ELSE 0 END) AS TERMINATED_COUNT
  FROM HR
  WHERE AGE>=18 
  GROUP BY DEPARTMENT
  ) AS SUBQUERY
ORDER BY TERMINATION_RATE DESC;



SELECT DEPARTMENT,
       TOTAL_COUNT,
       TERMINATED_COUNT,
       TERMINATED_COUNT / TOTAL_COUNT AS TERMINATION_RATE
FROM (
    SELECT DEPARTMENT,
           COUNT(*) AS TOTAL_COUNT,
           SUM(CASE WHEN TERMDATE IS NOT NULL AND TERMDATE <= CURDATE() THEN 1 ELSE 0 END) AS TERMINATED_COUNT
    FROM HR
    WHERE AGE >= 18
    GROUP BY DEPARTMENT
) AS SUBQUERY
ORDER BY TERMINATION_RATE DESC;


#Q.9 WHAT IS THE DISTRIBUTION OF EMPLOYEES ACROSS LOCATION BY CITY AND STATE?
;
SELECT LOCATION_STATE,COUNT(*) AS COUNT
FROM HR
WHERE AGE >=18 AND TERMDATE IS NULL
GROUP BY  LOCATION_STATE
ORDER BY COUNT DESC;

# Q.10 HOW HAS THE COMPANYS EMPLOYEE COUNT CHANGED OVER TIME BASED ON HIRE AND TERM DATES?

SELECT
YEAR,
HIRES,
TERMINATIONS,
HIRES-TERMINATIONS AS NET_CHANGE,
ROUND((HIRES-TERMINATIONS) /HIRES*100,2) AS NET_CHANGE_PERCENT
FROM(
SELECT YEAR(HIRE_DATE) AS YEAR,
COUNT(*) AS HIRES,
SUM(CASE WHEN TERMDATE IS NOT NULL AND TERMDATE<=CURDATE() THEN 1 ELSE 0 END) AS TERMINATIONS
FROM HR
WHERE AGE>=18 
GROUP BY YEAR(HIRE_DATE)
)AS SUBQUERY
ORDER BY YEAR ASC;


#Q.11 WHAT IS THE TENURE DISTRIBUTION FOR EACH DEPARTMENT?
SELECT DEPARTMENT,ROUND(AVG(DATEDIFF(TERMDATE,HIRE_DATE)/365),0) AS AVG_TENURE
FROM HR
WHERE TERMDATE<=CURDATE() AND TERMDATE IS NOT NULL AND AGE>=18
GROUP BY DEPARTMENT;