AS A 1ST STEP I HAVE TO CREATE THE DATABASE AND IMPORT THE DATA INTO IT AND GIVE NAME TO TABLE
AND SEE THE TABLE 


CREATE DATABASE PROJECTS;
USE PROJECTS;
SELECT*FROM HR;
THE NEXT THING IS DATA CLEANING PROCESS;
 
 # SO THE 1ST THING IS ID COLUMN NAME IS NOT IN A PROPER WAY SUPPOSE IF I WANT TO SEE ID COLUMN THEN 
 I HAVE WRITE THIS WORD AGAIN AND AGAIN AS IT INCLUDES THE SPECIAL CHARACTORS AS WELL SO ITS GET SOMETIMES MESSY SO I NEED TO CHANGE THE COLUMN NAME FOR THAT BELOW QUERY USED
 ;
 
 ALTER TABLE HR
 CHANGE COLUMN  ï»¿id ENP_ID VARCHAR(20) NULL;
 SELECT*FROM HR;
 
 # TO CHECK THE DATATYPES;
 
 DESC HR;
 
 AS U CAN SEE HERE BIRTHDATE,HIRE DATE , TERMDATE IS TEXT SO NEED TO CHANGE TO CORRECT DATATYPE;
 
 SELECT BIRTHDATE FROM HR;
 AND MOST IMP TAKE A LOOK AT THE BIRTHDATES THERE ARE DIFFRENT FORMAT DATES PRESENT SO NEED TO CONVERT IT TO SINGLE FORMAT
 ;
 
 UPDATE HR
SET BIRTHDATE = 
    CASE 
        WHEN BIRTHDATE LIKE '%/%' THEN DATE_FORMAT(STR_TO_DATE(BIRTHDATE, '%m/%d/%Y'), '%Y-%m-%d')
        WHEN BIRTHDATE LIKE '%-%' THEN DATE_FORMAT(STR_TO_DATE(BIRTHDATE, '%m-%d-%Y'), '%Y-%m-%d')
        ELSE DATE_FORMAT(STR_TO_DATE(BIRTHDATE, '%m-%d-%y'), '%Y-%m-%d')
    END;
    SELECT BIRTHDATE FROM HR;
    
    THIS IS HOW THE PREVIUOS DATE FORMAT CHANGED TO A STANDARD FORMAT;
    
    
    NOW CHANGE THE DATATYPE OF BIRTHDATE TEXT TO DATE
    ;
    ALTER TABLE HR
    MODIFY COLUMN BIRTHDATE DATE;
    
SELECT HIRE_DATE FROM HR;
AS U CAN SEE THE HIRE_DATE IS ALSO IN SAME FORMAT AS BIRTHDATE SO I NEED TO DO EXACT SAME CHANGES TO HIRE_DATE COLUMN TO SET A STANDARED FORMAT OF DATES
;

 
 UPDATE HR
SET HIRE_DATE = CASE
    WHEN HIRE_DATE LIKE "%/%" THEN DATE_FORMAT(STR_TO_DATE(HIRE_DATE, '%m/%d/%Y'), '%Y-%m-%d')
    WHEN HIRE_DATE LIKE "%-%" THEN DATE_FORMAT(STR_TO_DATE(HIRE_DATE, '%m-%d-%Y'), '%Y-%m-%d')
    ELSE NULL
END;
SELECT HIRE_DATE FROM HR;


SELECT TERMDATE FROM HR;

UPDATE HR
SET TERMDATE = NULL
WHERE TERMDATE = '';

UPDATE HR
SET TERMDATE = DATE_FORMAT(STR_TO_DATE(LEFT(TERMDATE, 19), '%Y-%m-%d %H:%i:%s'), '%Y-%m-%d')
WHERE TERMDATE IS  NOT NULL AND TERMDATE != '';
SELECT TERMDATE FROM HR;

ALTER TABLE HR
MODIFY COLUMN  TERMDATE DATE;
ALTER TABLE HR
MODIFY COLUMN HIRE_DATE DATE;

DESC HR;
AS WE CAN SEE I HAVE UPDATES THE DATATYPE AND SET TO STANDATED FORMAT DATES;


# TO ADD A COLUMN TO CALCULATE THE DIFFRENCES BETWEEN DATES;

SELECT*FROM HR;ALTER TABLE HR
ADD COLUMN AGE INT;
SELECT*FROM HR;

UPDATE HR
SET AGE= TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE());

SELECT BIRTHDATE,  AGE
FROM HR;

SELECT MIN(AGE) AS YOUNGEST, MAX(AGE) AS OLDEST FROM HR;
AS U CAN SEE THE AGE IS NEGATIVE I NEED TO FIX IT SO FOLLOWING OPERSTIONS USED
;
SELECT COUNT(*) FROM HR 
WHERE AGE<18;
